name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "eleventy.config.mjs"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Install dependencies
        uses: ./.github/workflows/actions/install-dependencies
      - name: Build site
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: noodlering
          path: _site
          retention-days: 1
  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: noodlering
      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PRODUCTION_PATH }}
          protocol: ftps
          port: 21
